<%@ Page Language="C#" AutoEventWireup="true" CodeFile="manageIndex.aspx.cs" Inherits="manageIndex" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>管理员首页</title>
    <link rel="stylesheet" href="layui/css/layui.css">
    <script src="layui/layui.js"></script>
    <link href="style/manageIndex.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="bootstrap-3.3.7-dist/css/bootstrap.css" rel="stylesheet">
    <script src="bootstrap-3.3.7-dist/js/jquery-3.2.1.js"></script>
    <script src="bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <style type="text/css">
        a 
        {
            text-align:center;
        }
        </style>
</head>
<body>
    <form id="form1" runat="server">
        <header>
        <div class="layui-header header">
            <div class="main">
                <a href="index.aspx"><span class="logoText">Blog</span></a>
                <ul class="layui-nav">
                    <li class="layui-nav-item layui-this"><a href="manageIndex.aspx">管理文章和评论</a></li>
                    <li class="layui-nav-item "><a href="addArticle.aspx">添加文章</a></li>
                    <li class="layui-nav-item"><a href="">管理留言</a></li>
                    <li class="layui-nav-item">
                        <asp:LinkButton ID="LinkButton2" runat="server" OnClick="LinkButton2_Click">退出</asp:LinkButton></li>
                </ul>
            </div>
        </div>
       </header>
        <script>
            layui.use('element', function () {
                var element = layui.element;
            });
        </script>
        <div class="local" style="margin-left:15%;margin-top:30px;text-align:center">
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" SelectedIndex="0" Height="267px" Width="971px" OnRowDataBound="GridView1_RowDataBound1" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" DataKeyNames="ArticleID" AutoGenerateDeleteButton="True">
             <Columns>
                 <asp:CommandField ShowEditButton="True" />
                <asp:BoundField DataField="ArticleID" HeaderText="ArticleID" SortExpression="ArticleID" InsertVisible="False" ReadOnly="True" />
<asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title">
</asp:BoundField>
                <asp:BoundField DataField="A_Content" HeaderText="A_Content" SortExpression="A_Content" >
                 <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                 </asp:BoundField>
                <asp:BoundField DataField="PublishedTime" HeaderText="PublishedTime" SortExpression="PublishedTime">
                </asp:BoundField>
            </Columns>
             <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
        </asp:GridView>
            </div>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:BlogConnectionString %>" SelectCommand="SELECT [Title], [A_Content], [PublishedTime], [ArticleID] FROM [Articles]" DeleteCommand="DELETE FROM [Articles] WHERE [ArticleID] = @ArticleID" InsertCommand="INSERT INTO [Articles] ([Title], [A_Content], [PublishedTime]) VALUES (@Title, @A_Content, @PublishedTime)" UpdateCommand="UPDATE [Articles] SET [Title] = @Title, [A_Content] = @A_Content, [PublishedTime] = @PublishedTime WHERE [ArticleID] = @ArticleID">
            <DeleteParameters>
                <asp:Parameter Name="ArticleID" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Title" Type="String" />
                <asp:Parameter Name="A_Content" Type="String" />
                <asp:Parameter Name="PublishedTime" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Title" Type="String" />
                <asp:Parameter Name="A_Content" Type="String" />
                <asp:Parameter Name="PublishedTime" Type="String" />
                <asp:Parameter Name="ArticleID" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
